# Configuration for CDK-Erigon with AggKit Prover
# Uses the new deploy_aggkit_prover flag to deploy aggkit-prover 
# independently of OP Stack

deployment_stages:
  deploy_l1: true
  deploy_zkevm_contracts_on_l1: true
  deploy_databases: true
  deploy_cdk_central_environment: true
  deploy_cdk_bridge_infra: true
  deploy_cdk_bridge_ui: false
  deploy_agglayer: true
  deploy_cdk_erigon_node: true
  # Don't deploy OP Stack
  deploy_optimism_rollup: false
  deploy_op_succinct: false
  # Deploy AggKit Prover independently
  deploy_aggkit_prover: true
  deploy_l2_contracts: true

args:
  verbosity: debug
  
  # Image versions
  zkevm_contracts_image: jhkimqd/zkevm-contracts:v10.1.0-rc.5-fork.12
  zkevm_prover_image: hermeznetwork/zkevm-prover:v8.0.0-RC16-fork.12
  cdk_node_image: ghcr.io/0xpolygon/cdk:0.5.4-rc1
  aggkit_image: ghcr.io/agglayer/aggkit:0.3.0-beta6
  agglayer_image: ghcr.io/agglayer/agglayer:0.3.0-rc.21
  aggkit_prover_image: ghcr.io/agglayer/aggkit-prover:0.1.0-rc.29
  
  # Configure for cdk-erigon as sequencer - using local build
  sequencer_type: erigon
  cdk_erigon_node_image: cdk-erigon:local
  
  # Consensus type - pessimistic works with aggkit-prover now
  consensus_contract_type: pessimistic
  
  # Verification keys for pessimistic consensus
  pp_vkey_hash: '0x00e60517ac96bf6255d81083269e72c14ad006e5f336f852f7ee3efb91b966be'
  pp_vkey_selector: '0x00000002'
  
  # AggKit prover configuration
  aggkit_prover_primary_prover: mock-prover
  aggkit_prover_log_level: debug
  
  # SP1 prover key for aggkit
  sp1_prover_key: "0x2857ca0e7748448f3a50469f7ffe55cde7299d5696aedd72cfe18a06fb856970"
  
  # General configuration
  erigon_strict_mode: false
  gas_token_enabled: false
  zkevm_use_real_verifier: false
  enable_normalcy: true
  
  # Chain configuration
  chain_name: type1-aggkit
  zkevm_rollup_chain_id: 2151908
  zkevm_rollup_id: 1
  
  # L1 configuration
  l1_chain_id: 271828
  l1_seconds_per_slot: 2
  l1_preset: minimal
  l1_funding_amount: "1000000ether"
  
  # L2 funding
  l2_accounts_to_fund: 10
  l2_funding_amount: "100ether" 